# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'phase9.ui'
#
# Created: Fri Mar  8 16:28:33 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(805, 841)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.about_tab = QtGui.QWidget()
        self.about_tab.setObjectName(_fromUtf8("about_tab"))
        self.gridLayout_9 = QtGui.QGridLayout(self.about_tab)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.about_tab)
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.gridLayout_9.addWidget(self.textBrowser_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.about_tab, _fromUtf8(""))
        self.registration_tab = QtGui.QWidget()
        self.registration_tab.setObjectName(_fromUtf8("registration_tab"))
        self.gridLayout_18 = QtGui.QGridLayout(self.registration_tab)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.Fixedframe_1 = QtGui.QFrame(self.registration_tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Fixedframe_1.setFont(font)
        self.Fixedframe_1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Fixedframe_1.setFrameShadow(QtGui.QFrame.Raised)
        self.Fixedframe_1.setObjectName(_fromUtf8("Fixedframe_1"))
        self.gridLayout_6 = QtGui.QGridLayout(self.Fixedframe_1)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.fixedCT_LE = QtGui.QLineEdit(self.Fixedframe_1)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fixedCT_LE.setFont(font)
        self.fixedCT_LE.setDragEnabled(True)
        self.fixedCT_LE.setObjectName(_fromUtf8("fixedCT_LE"))
        self.gridLayout_6.addWidget(self.fixedCT_LE, 1, 0, 1, 1)
        self.fixedCT_toolButton = QtGui.QToolButton(self.Fixedframe_1)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fixedCT_toolButton.setFont(font)
        self.fixedCT_toolButton.setObjectName(_fromUtf8("fixedCT_toolButton"))
        self.gridLayout_6.addWidget(self.fixedCT_toolButton, 1, 1, 1, 1)
        self.fixedCT_label = QtGui.QLabel(self.Fixedframe_1)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fixedCT_label.setFont(font)
        self.fixedCT_label.setObjectName(_fromUtf8("fixedCT_label"))
        self.gridLayout_6.addWidget(self.fixedCT_label, 1, 2, 1, 1)
        self.fixedSPECT_LE = QtGui.QLineEdit(self.Fixedframe_1)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fixedSPECT_LE.setFont(font)
        self.fixedSPECT_LE.setDragEnabled(True)
        self.fixedSPECT_LE.setObjectName(_fromUtf8("fixedSPECT_LE"))
        self.gridLayout_6.addWidget(self.fixedSPECT_LE, 2, 0, 1, 1)
        self.fixedSPECT_toolButton = QtGui.QToolButton(self.Fixedframe_1)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fixedSPECT_toolButton.setFont(font)
        self.fixedSPECT_toolButton.setObjectName(_fromUtf8("fixedSPECT_toolButton"))
        self.gridLayout_6.addWidget(self.fixedSPECT_toolButton, 2, 1, 1, 1)
        self.fixedCT_label_2 = QtGui.QLabel(self.Fixedframe_1)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fixedCT_label_2.setFont(font)
        self.fixedCT_label_2.setObjectName(_fromUtf8("fixedCT_label_2"))
        self.gridLayout_6.addWidget(self.fixedCT_label_2, 2, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.Fixedframe_1)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.Fixedframe_1, 0, 0, 1, 1)
        self.frame_11 = QtGui.QFrame(self.registration_tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.frame_11.setFont(font)
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.gridLayout_17 = QtGui.QGridLayout(self.frame_11)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.Reg_Chart_label = QtGui.QLabel(self.frame_11)
        self.Reg_Chart_label.setMinimumSize(QtCore.QSize(385, 405))
        self.Reg_Chart_label.setMaximumSize(QtCore.QSize(385, 405))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Reg_Chart_label.setFont(font)
        self.Reg_Chart_label.setFrameShape(QtGui.QFrame.Box)
        self.Reg_Chart_label.setText(_fromUtf8(""))
        self.Reg_Chart_label.setObjectName(_fromUtf8("Reg_Chart_label"))
        self.gridLayout_17.addWidget(self.Reg_Chart_label, 0, 0, 1, 1)
        self.frame_9 = QtGui.QFrame(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.frame_9.setFont(font)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_9)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.registerImages_button = QtGui.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.registerImages_button.setFont(font)
        self.registerImages_button.setObjectName(_fromUtf8("registerImages_button"))
        self.gridLayout_4.addWidget(self.registerImages_button, 0, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_4.addWidget(self.label_21, 1, 0, 1, 1)
        self.gridLayout_17.addWidget(self.frame_9, 1, 0, 1, 1)
        self.frame_10 = QtGui.QFrame(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.frame_10.setFont(font)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.gridLayout_16 = QtGui.QGridLayout(self.frame_10)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.label_25 = QtGui.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_16.addWidget(self.label_25, 1, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_16.addWidget(self.label_26, 2, 0, 1, 1)
        self.regNrun_pushButton = QtGui.QPushButton(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.regNrun_pushButton.setFont(font)
        self.regNrun_pushButton.setObjectName(_fromUtf8("regNrun_pushButton"))
        self.gridLayout_16.addWidget(self.regNrun_pushButton, 0, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_16.addWidget(self.label_27, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem, 4, 0, 1, 1)
        self.gridLayout_17.addWidget(self.frame_10, 2, 0, 1, 1)
        self.gridLayout_18.addWidget(self.frame_11, 0, 1, 7, 1)
        self.Fixedframe_2 = QtGui.QFrame(self.registration_tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Fixedframe_2.setFont(font)
        self.Fixedframe_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Fixedframe_2.setFrameShadow(QtGui.QFrame.Raised)
        self.Fixedframe_2.setObjectName(_fromUtf8("Fixedframe_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.Fixedframe_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.outputFixedSPECT_LE = QtGui.QLineEdit(self.Fixedframe_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.outputFixedSPECT_LE.setFont(font)
        self.outputFixedSPECT_LE.setDragEnabled(True)
        self.outputFixedSPECT_LE.setObjectName(_fromUtf8("outputFixedSPECT_LE"))
        self.gridLayout_5.addWidget(self.outputFixedSPECT_LE, 2, 0, 1, 1)
        self.outputFixedCT_LE = QtGui.QLineEdit(self.Fixedframe_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.outputFixedCT_LE.setFont(font)
        self.outputFixedCT_LE.setDragEnabled(True)
        self.outputFixedCT_LE.setObjectName(_fromUtf8("outputFixedCT_LE"))
        self.gridLayout_5.addWidget(self.outputFixedCT_LE, 1, 0, 1, 1)
        self.outputFixedCT_toolButton = QtGui.QToolButton(self.Fixedframe_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.outputFixedCT_toolButton.setFont(font)
        self.outputFixedCT_toolButton.setObjectName(_fromUtf8("outputFixedCT_toolButton"))
        self.gridLayout_5.addWidget(self.outputFixedCT_toolButton, 1, 1, 1, 1)
        self.oututCT_label_2 = QtGui.QLabel(self.Fixedframe_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.oututCT_label_2.setFont(font)
        self.oututCT_label_2.setObjectName(_fromUtf8("oututCT_label_2"))
        self.gridLayout_5.addWidget(self.oututCT_label_2, 1, 2, 1, 2)
        self.outputFixedSPECT_toolButton = QtGui.QToolButton(self.Fixedframe_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.outputFixedSPECT_toolButton.setFont(font)
        self.outputFixedSPECT_toolButton.setObjectName(_fromUtf8("outputFixedSPECT_toolButton"))
        self.gridLayout_5.addWidget(self.outputFixedSPECT_toolButton, 2, 1, 1, 1)
        self.oututSPECT_label_2 = QtGui.QLabel(self.Fixedframe_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.oututSPECT_label_2.setFont(font)
        self.oututSPECT_label_2.setObjectName(_fromUtf8("oututSPECT_label_2"))
        self.gridLayout_5.addWidget(self.oututSPECT_label_2, 2, 2, 1, 2)
        self.imNum_label = QtGui.QLabel(self.Fixedframe_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.imNum_label.setFont(font)
        self.imNum_label.setObjectName(_fromUtf8("imNum_label"))
        self.gridLayout_5.addWidget(self.imNum_label, 3, 2, 1, 1)
        self.convSPECTNum_Box = QtGui.QComboBox(self.Fixedframe_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.convSPECTNum_Box.setFont(font)
        self.convSPECTNum_Box.setObjectName(_fromUtf8("convSPECTNum_Box"))
        self.convSPECTNum_Box.addItem(_fromUtf8(""))
        self.convSPECTNum_Box.addItem(_fromUtf8(""))
        self.convSPECTNum_Box.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.convSPECTNum_Box, 3, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.Fixedframe_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.Fixedframe_2, 1, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.registration_tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_18.addWidget(self.label_18, 2, 0, 1, 1)
        self.frame = QtGui.QFrame(self.registration_tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.movingCT_LE = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.movingCT_LE.setFont(font)
        self.movingCT_LE.setDragEnabled(True)
        self.movingCT_LE.setObjectName(_fromUtf8("movingCT_LE"))
        self.gridLayout_7.addWidget(self.movingCT_LE, 1, 0, 1, 1)
        self.movingCT_toolButton = QtGui.QToolButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.movingCT_toolButton.setFont(font)
        self.movingCT_toolButton.setObjectName(_fromUtf8("movingCT_toolButton"))
        self.gridLayout_7.addWidget(self.movingCT_toolButton, 1, 1, 1, 1)
        self.movingCT_label = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.movingCT_label.setFont(font)
        self.movingCT_label.setObjectName(_fromUtf8("movingCT_label"))
        self.gridLayout_7.addWidget(self.movingCT_label, 1, 2, 1, 1)
        self.movingSPECT_LE = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.movingSPECT_LE.setFont(font)
        self.movingSPECT_LE.setDragEnabled(True)
        self.movingSPECT_LE.setObjectName(_fromUtf8("movingSPECT_LE"))
        self.gridLayout_7.addWidget(self.movingSPECT_LE, 2, 0, 1, 1)
        self.movingSPECT_toolButton = QtGui.QToolButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.movingSPECT_toolButton.setFont(font)
        self.movingSPECT_toolButton.setObjectName(_fromUtf8("movingSPECT_toolButton"))
        self.gridLayout_7.addWidget(self.movingSPECT_toolButton, 2, 1, 1, 1)
        self.movingSPECT_label = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.movingSPECT_label.setFont(font)
        self.movingSPECT_label.setObjectName(_fromUtf8("movingSPECT_label"))
        self.gridLayout_7.addWidget(self.movingSPECT_label, 2, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_7.addWidget(self.label_15, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.frame, 3, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.registration_tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.outputCT_LE = QtGui.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.outputCT_LE.setFont(font)
        self.outputCT_LE.setDragEnabled(True)
        self.outputCT_LE.setObjectName(_fromUtf8("outputCT_LE"))
        self.gridLayout_8.addWidget(self.outputCT_LE, 1, 0, 1, 1)
        self.outputCT_toolButton = QtGui.QToolButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.outputCT_toolButton.setFont(font)
        self.outputCT_toolButton.setObjectName(_fromUtf8("outputCT_toolButton"))
        self.gridLayout_8.addWidget(self.outputCT_toolButton, 1, 1, 1, 1)
        self.oututCT_label = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.oututCT_label.setFont(font)
        self.oututCT_label.setObjectName(_fromUtf8("oututCT_label"))
        self.gridLayout_8.addWidget(self.oututCT_label, 1, 2, 1, 2)
        self.outputSPECT_LE = QtGui.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.outputSPECT_LE.setFont(font)
        self.outputSPECT_LE.setDragEnabled(True)
        self.outputSPECT_LE.setObjectName(_fromUtf8("outputSPECT_LE"))
        self.gridLayout_8.addWidget(self.outputSPECT_LE, 2, 0, 1, 1)
        self.outputSPECT_toolButton = QtGui.QToolButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.outputSPECT_toolButton.setFont(font)
        self.outputSPECT_toolButton.setObjectName(_fromUtf8("outputSPECT_toolButton"))
        self.gridLayout_8.addWidget(self.outputSPECT_toolButton, 2, 1, 1, 1)
        self.oututSPECT_label = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.oututSPECT_label.setFont(font)
        self.oututSPECT_label.setObjectName(_fromUtf8("oututSPECT_label"))
        self.gridLayout_8.addWidget(self.oututSPECT_label, 2, 2, 1, 2)
        self.imNum_label_2 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.imNum_label_2.setFont(font)
        self.imNum_label_2.setObjectName(_fromUtf8("imNum_label_2"))
        self.gridLayout_8.addWidget(self.imNum_label_2, 3, 2, 1, 1)
        self.regSPECTNum_Box = QtGui.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.regSPECTNum_Box.setFont(font)
        self.regSPECTNum_Box.setObjectName(_fromUtf8("regSPECTNum_Box"))
        self.regSPECTNum_Box.addItem(_fromUtf8(""))
        self.regSPECTNum_Box.addItem(_fromUtf8(""))
        self.regSPECTNum_Box.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.regSPECTNum_Box, 3, 3, 1, 1)
        self.label_16 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_8.addWidget(self.label_16, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.frame_2, 4, 0, 1, 1)
        self.frame_8 = QtGui.QFrame(self.registration_tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.frame_8.setFont(font)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.gridLayout_14 = QtGui.QGridLayout(self.frame_8)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.movingCT_toolButton_2 = QtGui.QToolButton(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.movingCT_toolButton_2.setFont(font)
        self.movingCT_toolButton_2.setObjectName(_fromUtf8("movingCT_toolButton_2"))
        self.gridLayout_14.addWidget(self.movingCT_toolButton_2, 1, 1, 1, 1)
        self.movingCT_LE_2 = QtGui.QLineEdit(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.movingCT_LE_2.setFont(font)
        self.movingCT_LE_2.setDragEnabled(True)
        self.movingCT_LE_2.setObjectName(_fromUtf8("movingCT_LE_2"))
        self.gridLayout_14.addWidget(self.movingCT_LE_2, 1, 0, 1, 1)
        self.movingCT_label_2 = QtGui.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.movingCT_label_2.setFont(font)
        self.movingCT_label_2.setObjectName(_fromUtf8("movingCT_label_2"))
        self.gridLayout_14.addWidget(self.movingCT_label_2, 1, 2, 1, 1)
        self.movingSPECT_LE_2 = QtGui.QLineEdit(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.movingSPECT_LE_2.setFont(font)
        self.movingSPECT_LE_2.setDragEnabled(True)
        self.movingSPECT_LE_2.setObjectName(_fromUtf8("movingSPECT_LE_2"))
        self.gridLayout_14.addWidget(self.movingSPECT_LE_2, 2, 0, 1, 1)
        self.movingSPECT_toolButton_2 = QtGui.QToolButton(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.movingSPECT_toolButton_2.setFont(font)
        self.movingSPECT_toolButton_2.setObjectName(_fromUtf8("movingSPECT_toolButton_2"))
        self.gridLayout_14.addWidget(self.movingSPECT_toolButton_2, 2, 1, 1, 1)
        self.movingSPECT_label_2 = QtGui.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.movingSPECT_label_2.setFont(font)
        self.movingSPECT_label_2.setObjectName(_fromUtf8("movingSPECT_label_2"))
        self.gridLayout_14.addWidget(self.movingSPECT_label_2, 2, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_14.addWidget(self.label_24, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.frame_8, 5, 0, 1, 1)
        self.frame_7 = QtGui.QFrame(self.registration_tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.frame_7.setFont(font)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.gridLayout_10 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.outputCT_LE_2 = QtGui.QLineEdit(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.outputCT_LE_2.setFont(font)
        self.outputCT_LE_2.setDragEnabled(True)
        self.outputCT_LE_2.setObjectName(_fromUtf8("outputCT_LE_2"))
        self.gridLayout_10.addWidget(self.outputCT_LE_2, 1, 0, 1, 1)
        self.outputCT_toolButton_2 = QtGui.QToolButton(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.outputCT_toolButton_2.setFont(font)
        self.outputCT_toolButton_2.setObjectName(_fromUtf8("outputCT_toolButton_2"))
        self.gridLayout_10.addWidget(self.outputCT_toolButton_2, 1, 1, 1, 1)
        self.oututCT_label_3 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.oututCT_label_3.setFont(font)
        self.oututCT_label_3.setObjectName(_fromUtf8("oututCT_label_3"))
        self.gridLayout_10.addWidget(self.oututCT_label_3, 1, 2, 1, 2)
        self.outputSPECT_LE_2 = QtGui.QLineEdit(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.outputSPECT_LE_2.setFont(font)
        self.outputSPECT_LE_2.setDragEnabled(True)
        self.outputSPECT_LE_2.setObjectName(_fromUtf8("outputSPECT_LE_2"))
        self.gridLayout_10.addWidget(self.outputSPECT_LE_2, 2, 0, 1, 1)
        self.outputSPECT_toolButton_2 = QtGui.QToolButton(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.outputSPECT_toolButton_2.setFont(font)
        self.outputSPECT_toolButton_2.setObjectName(_fromUtf8("outputSPECT_toolButton_2"))
        self.gridLayout_10.addWidget(self.outputSPECT_toolButton_2, 2, 1, 1, 1)
        self.oututSPECT_label_3 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.oututSPECT_label_3.setFont(font)
        self.oututSPECT_label_3.setObjectName(_fromUtf8("oututSPECT_label_3"))
        self.gridLayout_10.addWidget(self.oututSPECT_label_3, 2, 2, 1, 2)
        self.imNum_label_3 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.imNum_label_3.setFont(font)
        self.imNum_label_3.setObjectName(_fromUtf8("imNum_label_3"))
        self.gridLayout_10.addWidget(self.imNum_label_3, 3, 2, 1, 1)
        self.regSPECTNum_Box_2 = QtGui.QComboBox(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.regSPECTNum_Box_2.setFont(font)
        self.regSPECTNum_Box_2.setObjectName(_fromUtf8("regSPECTNum_Box_2"))
        self.regSPECTNum_Box_2.addItem(_fromUtf8(""))
        self.regSPECTNum_Box_2.addItem(_fromUtf8(""))
        self.regSPECTNum_Box_2.addItem(_fromUtf8(""))
        self.gridLayout_10.addWidget(self.regSPECTNum_Box_2, 3, 3, 1, 1)
        self.label_23 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_10.addWidget(self.label_23, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.frame_7, 6, 0, 1, 1)
        self.tabWidget.addTab(self.registration_tab, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.formLayout = QtGui.QFormLayout(self.tab)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.defParam_label = QtGui.QLabel(self.tab)
        self.defParam_label.setObjectName(_fromUtf8("defParam_label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.defParam_label)
        self.res1_label = QtGui.QLabel(self.tab)
        self.res1_label.setObjectName(_fromUtf8("res1_label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.res1_label)
        self.res1combo_label = QtGui.QLabel(self.tab)
        self.res1combo_label.setObjectName(_fromUtf8("res1combo_label"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.res1combo_label)
        self.res1_comboBox = QtGui.QComboBox(self.tab)
        self.res1_comboBox.setObjectName(_fromUtf8("res1_comboBox"))
        self.res1_comboBox.addItem(_fromUtf8(""))
        self.res1_comboBox.addItem(_fromUtf8(""))
        self.res1_comboBox.addItem(_fromUtf8(""))
        self.res1_comboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.res1_comboBox)
        self.res1gridcombo_label = QtGui.QLabel(self.tab)
        self.res1gridcombo_label.setObjectName(_fromUtf8("res1gridcombo_label"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.res1gridcombo_label)
        self.res1grid_comboBox = QtGui.QComboBox(self.tab)
        self.res1grid_comboBox.setObjectName(_fromUtf8("res1grid_comboBox"))
        self.res1grid_comboBox.addItem(_fromUtf8(""))
        self.res1grid_comboBox.addItem(_fromUtf8(""))
        self.res1grid_comboBox.addItem(_fromUtf8(""))
        self.res1grid_comboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.res1grid_comboBox)
        self.res1iterations_label = QtGui.QLabel(self.tab)
        self.res1iterations_label.setObjectName(_fromUtf8("res1iterations_label"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.res1iterations_label)
        self.res1_lineEdit = QtGui.QLineEdit(self.tab)
        self.res1_lineEdit.setObjectName(_fromUtf8("res1_lineEdit"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.res1_lineEdit)
        self.res2_label = QtGui.QLabel(self.tab)
        self.res2_label.setObjectName(_fromUtf8("res2_label"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.res2_label)
        self.res1_comboBox_2 = QtGui.QComboBox(self.tab)
        self.res1_comboBox_2.setObjectName(_fromUtf8("res1_comboBox_2"))
        self.res1_comboBox_2.addItem(_fromUtf8(""))
        self.res1_comboBox_2.addItem(_fromUtf8(""))
        self.res1_comboBox_2.addItem(_fromUtf8(""))
        self.res1_comboBox_2.addItem(_fromUtf8(""))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.res1_comboBox_2)
        self.res2gridcombo_label = QtGui.QLabel(self.tab)
        self.res2gridcombo_label.setObjectName(_fromUtf8("res2gridcombo_label"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.res2gridcombo_label)
        self.res2grid_comboBox = QtGui.QComboBox(self.tab)
        self.res2grid_comboBox.setObjectName(_fromUtf8("res2grid_comboBox"))
        self.res2grid_comboBox.addItem(_fromUtf8(""))
        self.res2grid_comboBox.addItem(_fromUtf8(""))
        self.res2grid_comboBox.addItem(_fromUtf8(""))
        self.res2grid_comboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.res2grid_comboBox)
        self.res2iterations_label = QtGui.QLabel(self.tab)
        self.res2iterations_label.setObjectName(_fromUtf8("res2iterations_label"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.LabelRole, self.res2iterations_label)
        self.res2_lineEdit = QtGui.QLineEdit(self.tab)
        self.res2_lineEdit.setObjectName(_fromUtf8("res2_lineEdit"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.LabelRole, self.res2_lineEdit)
        self.res2iterations_label_2 = QtGui.QLabel(self.tab)
        self.res2iterations_label_2.setObjectName(_fromUtf8("res2iterations_label_2"))
        self.formLayout.setWidget(16, QtGui.QFormLayout.LabelRole, self.res2iterations_label_2)
        self.bendingPenalty_lineEdit = QtGui.QLineEdit(self.tab)
        self.bendingPenalty_lineEdit.setObjectName(_fromUtf8("bendingPenalty_lineEdit"))
        self.formLayout.setWidget(17, QtGui.QFormLayout.LabelRole, self.bendingPenalty_lineEdit)
        self.res2combo_label = QtGui.QLabel(self.tab)
        self.res2combo_label.setObjectName(_fromUtf8("res2combo_label"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.res2combo_label)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.input_tab = QtGui.QWidget()
        self.input_tab.setObjectName(_fromUtf8("input_tab"))
        self.gridLayout_15 = QtGui.QGridLayout(self.input_tab)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.frame_5 = QtGui.QFrame(self.input_tab)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_12 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_3 = QtGui.QLabel(self.frame_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_12.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.frame_5)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_12.addWidget(self.label_20, 1, 0, 1, 1)
        self.image3_lineedit = QtGui.QLineEdit(self.frame_5)
        self.image3_lineedit.setMinimumSize(QtCore.QSize(200, 0))
        self.image3_lineedit.setDragEnabled(True)
        self.image3_lineedit.setObjectName(_fromUtf8("image3_lineedit"))
        self.gridLayout_12.addWidget(self.image3_lineedit, 1, 1, 1, 1)
        self.im3_toolButton = QtGui.QToolButton(self.frame_5)
        self.im3_toolButton.setObjectName(_fromUtf8("im3_toolButton"))
        self.gridLayout_12.addWidget(self.im3_toolButton, 1, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_12.addWidget(self.label_6, 1, 3, 1, 1)
        self.im3_PI_lineedit = QtGui.QLineEdit(self.frame_5)
        self.im3_PI_lineedit.setObjectName(_fromUtf8("im3_PI_lineedit"))
        self.gridLayout_12.addWidget(self.im3_PI_lineedit, 1, 4, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem1, 1, 5, 1, 1)
        self.gridLayout_15.addWidget(self.frame_5, 2, 0, 1, 4)
        self.label_22 = QtGui.QLabel(self.input_tab)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_15.addWidget(self.label_22, 4, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.input_tab)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.comboBox, 4, 1, 1, 1)
        self.halflife_lineedit = QtGui.QLineEdit(self.input_tab)
        self.halflife_lineedit.setObjectName(_fromUtf8("halflife_lineedit"))
        self.gridLayout_15.addWidget(self.halflife_lineedit, 3, 2, 1, 1)
        self.frame_3 = QtGui.QFrame(self.input_tab)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout = QtGui.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.frame_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.frame_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 1, 0, 1, 1)
        self.image1_lineedit = QtGui.QLineEdit(self.frame_3)
        self.image1_lineedit.setMinimumSize(QtCore.QSize(200, 0))
        self.image1_lineedit.setDragEnabled(True)
        self.image1_lineedit.setObjectName(_fromUtf8("image1_lineedit"))
        self.gridLayout.addWidget(self.image1_lineedit, 1, 1, 1, 1)
        self.im1_toolButton = QtGui.QToolButton(self.frame_3)
        self.im1_toolButton.setObjectName(_fromUtf8("im1_toolButton"))
        self.gridLayout.addWidget(self.im1_toolButton, 1, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.im1_PI_lineedit = QtGui.QLineEdit(self.frame_3)
        self.im1_PI_lineedit.setObjectName(_fromUtf8("im1_PI_lineedit"))
        self.gridLayout.addWidget(self.im1_PI_lineedit, 1, 4, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 5, 1, 1)
        self.gridLayout_15.addWidget(self.frame_3, 0, 0, 1, 4)
        self.isotope_comboBox = QtGui.QComboBox(self.input_tab)
        self.isotope_comboBox.setObjectName(_fromUtf8("isotope_comboBox"))
        self.isotope_comboBox.addItem(_fromUtf8(""))
        self.isotope_comboBox.addItem(_fromUtf8(""))
        self.isotope_comboBox.addItem(_fromUtf8(""))
        self.isotope_comboBox.addItem(_fromUtf8(""))
        self.isotope_comboBox.addItem(_fromUtf8(""))
        self.isotope_comboBox.addItem(_fromUtf8(""))
        self.isotope_comboBox.addItem(_fromUtf8(""))
        self.isotope_comboBox.addItem(_fromUtf8(""))
        self.isotope_comboBox.addItem(_fromUtf8(""))
        self.isotope_comboBox.addItem(_fromUtf8(""))
        self.isotope_comboBox.addItem(_fromUtf8(""))
        self.isotope_comboBox.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.isotope_comboBox, 3, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.input_tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_15.addWidget(self.label_8, 3, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.input_tab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_15.addWidget(self.label_7, 3, 0, 1, 1)
        self.frame_4 = QtGui.QFrame(self.input_tab)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_11 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_2 = QtGui.QLabel(self.frame_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_11.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.frame_4)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_11.addWidget(self.label_19, 1, 0, 1, 1)
        self.image2_lineedit = QtGui.QLineEdit(self.frame_4)
        self.image2_lineedit.setMinimumSize(QtCore.QSize(200, 0))
        self.image2_lineedit.setDragEnabled(True)
        self.image2_lineedit.setObjectName(_fromUtf8("image2_lineedit"))
        self.gridLayout_11.addWidget(self.image2_lineedit, 1, 1, 1, 1)
        self.im2_toolButton = QtGui.QToolButton(self.frame_4)
        self.im2_toolButton.setObjectName(_fromUtf8("im2_toolButton"))
        self.gridLayout_11.addWidget(self.im2_toolButton, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_11.addWidget(self.label_5, 1, 3, 1, 1)
        self.im2_PI_lineedit = QtGui.QLineEdit(self.frame_4)
        self.im2_PI_lineedit.setObjectName(_fromUtf8("im2_PI_lineedit"))
        self.gridLayout_11.addWidget(self.im2_PI_lineedit, 1, 4, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem3, 1, 5, 1, 1)
        self.gridLayout_15.addWidget(self.frame_4, 1, 0, 1, 4)
        self.frame_6 = QtGui.QFrame(self.input_tab)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_13 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_9 = QtGui.QLabel(self.frame_6)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_13.addWidget(self.label_9, 0, 0, 1, 2)
        self.outputimage_lineedit = QtGui.QLineEdit(self.frame_6)
        self.outputimage_lineedit.setDragEnabled(True)
        self.outputimage_lineedit.setObjectName(_fromUtf8("outputimage_lineedit"))
        self.gridLayout_13.addWidget(self.outputimage_lineedit, 0, 2, 1, 1)
        self.outputimage_toolButton = QtGui.QToolButton(self.frame_6)
        self.outputimage_toolButton.setObjectName(_fromUtf8("outputimage_toolButton"))
        self.gridLayout_13.addWidget(self.outputimage_toolButton, 0, 3, 1, 1)
        self.save_fit_checkBox = QtGui.QCheckBox(self.frame_6)
        self.save_fit_checkBox.setObjectName(_fromUtf8("save_fit_checkBox"))
        self.gridLayout_13.addWidget(self.save_fit_checkBox, 1, 0, 1, 1)
        self.gridLayout_15.addWidget(self.frame_6, 5, 0, 1, 4)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem4, 6, 0, 1, 1)
        self.tabWidget.addTab(self.input_tab, _fromUtf8(""))
        self.kinetics_tab = QtGui.QWidget()
        self.kinetics_tab.setObjectName(_fromUtf8("kinetics_tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.kinetics_tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.runVRAK_pushButton = QtGui.QPushButton(self.kinetics_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.runVRAK_pushButton.setFont(font)
        self.runVRAK_pushButton.setObjectName(_fromUtf8("runVRAK_pushButton"))
        self.gridLayout_2.addWidget(self.runVRAK_pushButton, 0, 0, 1, 1)
        self.cancel_Button = QtGui.QPushButton(self.kinetics_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.cancel_Button.setFont(font)
        self.cancel_Button.setObjectName(_fromUtf8("cancel_Button"))
        self.gridLayout_2.addWidget(self.cancel_Button, 0, 1, 1, 1)
        self.terminal_textBrowser = QtGui.QTextBrowser(self.kinetics_tab)
        self.terminal_textBrowser.setMinimumSize(QtCore.QSize(450, 500))
        self.terminal_textBrowser.setMaximumSize(QtCore.QSize(700, 16777215))
        self.terminal_textBrowser.setObjectName(_fromUtf8("terminal_textBrowser"))
        self.gridLayout_2.addWidget(self.terminal_textBrowser, 0, 2, 3, 1)
        self.progressBar = QtGui.QProgressBar(self.kinetics_tab)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_2.addWidget(self.progressBar, 1, 0, 1, 2)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 3, 2, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 2, 1, 1, 1)
        self.tabWidget.addTab(self.kinetics_tab, _fromUtf8(""))
        self.config_tab = QtGui.QWidget()
        self.config_tab.setObjectName(_fromUtf8("config_tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.config_tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.elastixPath_LE = QtGui.QLineEdit(self.config_tab)
        self.elastixPath_LE.setObjectName(_fromUtf8("elastixPath_LE"))
        self.gridLayout_3.addWidget(self.elastixPath_LE, 0, 0, 1, 1)
        self.elastixPath_toolButton = QtGui.QToolButton(self.config_tab)
        self.elastixPath_toolButton.setObjectName(_fromUtf8("elastixPath_toolButton"))
        self.gridLayout_3.addWidget(self.elastixPath_toolButton, 0, 1, 1, 1)
        self.elastixPath_label = QtGui.QLabel(self.config_tab)
        self.elastixPath_label.setObjectName(_fromUtf8("elastixPath_label"))
        self.gridLayout_3.addWidget(self.elastixPath_label, 0, 2, 1, 1)
        self.transformixPath_LE = QtGui.QLineEdit(self.config_tab)
        self.transformixPath_LE.setObjectName(_fromUtf8("transformixPath_LE"))
        self.gridLayout_3.addWidget(self.transformixPath_LE, 1, 0, 1, 1)
        self.transformixPath_toolButton = QtGui.QToolButton(self.config_tab)
        self.transformixPath_toolButton.setObjectName(_fromUtf8("transformixPath_toolButton"))
        self.gridLayout_3.addWidget(self.transformixPath_toolButton, 1, 1, 1, 1)
        self.transformixPath_label = QtGui.QLabel(self.config_tab)
        self.transformixPath_label.setObjectName(_fromUtf8("transformixPath_label"))
        self.gridLayout_3.addWidget(self.transformixPath_label, 1, 2, 1, 1)
        self.transformixPath_LE_2 = QtGui.QLineEdit(self.config_tab)
        self.transformixPath_LE_2.setObjectName(_fromUtf8("transformixPath_LE_2"))
        self.gridLayout_3.addWidget(self.transformixPath_LE_2, 2, 0, 1, 1)
        self.transformixPath_toolButton_2 = QtGui.QToolButton(self.config_tab)
        self.transformixPath_toolButton_2.setObjectName(_fromUtf8("transformixPath_toolButton_2"))
        self.gridLayout_3.addWidget(self.transformixPath_toolButton_2, 2, 1, 1, 1)
        self.transformixPath_label_2 = QtGui.QLabel(self.config_tab)
        self.transformixPath_label_2.setObjectName(_fromUtf8("transformixPath_label_2"))
        self.gridLayout_3.addWidget(self.transformixPath_label_2, 2, 2, 1, 1)
        self.configure_pushButton = QtGui.QPushButton(self.config_tab)
        self.configure_pushButton.setObjectName(_fromUtf8("configure_pushButton"))
        self.gridLayout_3.addWidget(self.configure_pushButton, 3, 0, 1, 1)
        self.configure_textBrowser = QtGui.QTextBrowser(self.config_tab)
        self.configure_textBrowser.setObjectName(_fromUtf8("configure_textBrowser"))
        self.gridLayout_3.addWidget(self.configure_textBrowser, 4, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem7, 5, 0, 1, 1)
        self.tabWidget.addTab(self.config_tab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.convSPECTNum_Box.setCurrentIndex(0)
        self.regSPECTNum_Box.setCurrentIndex(1)
        self.regSPECTNum_Box_2.setCurrentIndex(2)
        self.res1_comboBox.setCurrentIndex(1)
        self.res1grid_comboBox.setCurrentIndex(1)
        self.res1_comboBox_2.setCurrentIndex(1)
        self.res2grid_comboBox.setCurrentIndex(1)
        self.comboBox.setCurrentIndex(7)
        self.isotope_comboBox.setCurrentIndex(10)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.textBrowser_2)
        MainWindow.setTabOrder(self.textBrowser_2, self.fixedCT_LE)
        MainWindow.setTabOrder(self.fixedCT_LE, self.fixedCT_toolButton)
        MainWindow.setTabOrder(self.fixedCT_toolButton, self.fixedSPECT_LE)
        MainWindow.setTabOrder(self.fixedSPECT_LE, self.fixedSPECT_toolButton)
        MainWindow.setTabOrder(self.fixedSPECT_toolButton, self.outputFixedCT_LE)
        MainWindow.setTabOrder(self.outputFixedCT_LE, self.outputFixedCT_toolButton)
        MainWindow.setTabOrder(self.outputFixedCT_toolButton, self.outputFixedSPECT_LE)
        MainWindow.setTabOrder(self.outputFixedSPECT_LE, self.outputFixedSPECT_toolButton)
        MainWindow.setTabOrder(self.outputFixedSPECT_toolButton, self.convSPECTNum_Box)
        MainWindow.setTabOrder(self.convSPECTNum_Box, self.movingCT_LE)
        MainWindow.setTabOrder(self.movingCT_LE, self.movingCT_toolButton)
        MainWindow.setTabOrder(self.movingCT_toolButton, self.movingSPECT_LE)
        MainWindow.setTabOrder(self.movingSPECT_LE, self.movingSPECT_toolButton)
        MainWindow.setTabOrder(self.movingSPECT_toolButton, self.outputCT_LE)
        MainWindow.setTabOrder(self.outputCT_LE, self.outputCT_toolButton)
        MainWindow.setTabOrder(self.outputCT_toolButton, self.outputSPECT_LE)
        MainWindow.setTabOrder(self.outputSPECT_LE, self.outputSPECT_toolButton)
        MainWindow.setTabOrder(self.outputSPECT_toolButton, self.regSPECTNum_Box)
        MainWindow.setTabOrder(self.regSPECTNum_Box, self.movingCT_LE_2)
        MainWindow.setTabOrder(self.movingCT_LE_2, self.movingCT_toolButton_2)
        MainWindow.setTabOrder(self.movingCT_toolButton_2, self.movingSPECT_LE_2)
        MainWindow.setTabOrder(self.movingSPECT_LE_2, self.movingSPECT_toolButton_2)
        MainWindow.setTabOrder(self.movingSPECT_toolButton_2, self.outputCT_LE_2)
        MainWindow.setTabOrder(self.outputCT_LE_2, self.outputCT_toolButton_2)
        MainWindow.setTabOrder(self.outputCT_toolButton_2, self.outputSPECT_LE_2)
        MainWindow.setTabOrder(self.outputSPECT_LE_2, self.outputSPECT_toolButton_2)
        MainWindow.setTabOrder(self.outputSPECT_toolButton_2, self.regSPECTNum_Box_2)
        MainWindow.setTabOrder(self.regSPECTNum_Box_2, self.registerImages_button)
        MainWindow.setTabOrder(self.registerImages_button, self.regNrun_pushButton)
        MainWindow.setTabOrder(self.regNrun_pushButton, self.res1_comboBox)
        MainWindow.setTabOrder(self.res1_comboBox, self.res1grid_comboBox)
        MainWindow.setTabOrder(self.res1grid_comboBox, self.res1_lineEdit)
        MainWindow.setTabOrder(self.res1_lineEdit, self.res1_comboBox_2)
        MainWindow.setTabOrder(self.res1_comboBox_2, self.res2grid_comboBox)
        MainWindow.setTabOrder(self.res2grid_comboBox, self.res2_lineEdit)
        MainWindow.setTabOrder(self.res2_lineEdit, self.bendingPenalty_lineEdit)
        MainWindow.setTabOrder(self.bendingPenalty_lineEdit, self.image1_lineedit)
        MainWindow.setTabOrder(self.image1_lineedit, self.im1_toolButton)
        MainWindow.setTabOrder(self.im1_toolButton, self.im1_PI_lineedit)
        MainWindow.setTabOrder(self.im1_PI_lineedit, self.image2_lineedit)
        MainWindow.setTabOrder(self.image2_lineedit, self.im2_toolButton)
        MainWindow.setTabOrder(self.im2_toolButton, self.im2_PI_lineedit)
        MainWindow.setTabOrder(self.im2_PI_lineedit, self.image3_lineedit)
        MainWindow.setTabOrder(self.image3_lineedit, self.im3_toolButton)
        MainWindow.setTabOrder(self.im3_toolButton, self.im3_PI_lineedit)
        MainWindow.setTabOrder(self.im3_PI_lineedit, self.isotope_comboBox)
        MainWindow.setTabOrder(self.isotope_comboBox, self.halflife_lineedit)
        MainWindow.setTabOrder(self.halflife_lineedit, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.outputimage_lineedit)
        MainWindow.setTabOrder(self.outputimage_lineedit, self.outputimage_toolButton)
        MainWindow.setTabOrder(self.outputimage_toolButton, self.save_fit_checkBox)
        MainWindow.setTabOrder(self.save_fit_checkBox, self.runVRAK_pushButton)
        MainWindow.setTabOrder(self.runVRAK_pushButton, self.cancel_Button)
        MainWindow.setTabOrder(self.cancel_Button, self.terminal_textBrowser)
        MainWindow.setTabOrder(self.terminal_textBrowser, self.elastixPath_LE)
        MainWindow.setTabOrder(self.elastixPath_LE, self.elastixPath_toolButton)
        MainWindow.setTabOrder(self.elastixPath_toolButton, self.transformixPath_LE)
        MainWindow.setTabOrder(self.transformixPath_LE, self.transformixPath_toolButton)
        MainWindow.setTabOrder(self.transformixPath_toolButton, self.transformixPath_LE_2)
        MainWindow.setTabOrder(self.transformixPath_LE_2, self.transformixPath_toolButton_2)
        MainWindow.setTabOrder(self.transformixPath_toolButton_2, self.configure_pushButton)
        MainWindow.setTabOrder(self.configure_pushButton, self.configure_textBrowser)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "VRAK - Radionuclide Dosimetry", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser_2.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">To Perform Dosimetry using Serial SPECT/PET images:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">1) Co-register Images (Optionally edit Registration Params)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">    </span><span style=\" font-size:11pt;\">-VRAK will use built-in registration parameters to batch run Elastix.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    -Rigid+Deformable registration of CT volumes</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    -Warp Functional Volumes to match</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    -Optionally: Adjust deformable registration parameters</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    -Output in ITK (*.mhd format) necessary for kinetics processing routine</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">2) Run Voxelized Kinetics Dosimetry [Input &amp; Process Tabs]</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    -Kinetics Input Tab: Image files and times (2 or 3 timepoint), isotope halflife</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    -Auto-populated from registration tab</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    -Process Kinetics Tab: Runs the processing routine</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    -Output: *.mhd image with disintigrations per voxel (Bq*Hrs/mL)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'arial,sans-serif\'; font-size:11pt; color:#000000; background-color:#ffffff;\">The Voxelized Registration and Kinetics software (&quot;VRAK&quot;) has been developed with the support of the Victorian Government through the Victorian Cancer Agency Lutetium Therapy Grant for the</span><span style=\" font-family:\'arial,sans-serif\'; font-size:11pt; color:#000000;\"> </span><a href=\"http://www.petermac.org/Research/MolecularImagingandTargetedTherapeutics\"><span style=\" font-family:\'arial,sans-serif\'; font-size:11pt; text-decoration: underline; color:#0000cc;\">Molecular Imaging and Targeted Therapeutics Group</span></a><span style=\" font-family:\'arial,sans-serif\'; font-size:11pt; color:#000000;\"> at </span><a href=\"http://www.petermac.org/\"><span style=\" font-family:\'arial,sans-serif\'; font-size:11pt; text-decoration: underline; color:#0000cc;\">Peter MacCallum Cancer Centre</span></a><span style=\" font-family:\'arial,sans-serif\'; font-size:11pt; color:#000000;\"> in Melbourne, Australia.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'arial,sans-serif\'; font-size:11pt; color:#000000; background-color:#ffffff;\">Peter MacCallum Cancer Centre is the owner of the copyright in VRAK.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'arial,sans-serif\'; font-size:11pt; color:#000000; background-color:#ffffff;\">For questions, feedback, or to collaborate on development visit the </span><a href=\"http://code.google.com/p/vrak-dosimetry/\"><span style=\" font-size:11pt; text-decoration: underline; color:#0000ff;\">Project Site</span></a><span style=\" font-family:\'arial,sans-serif\'; font-size:11pt; color:#000000; background-color:#ffffff;\"> or email </span><a href=\"price.jackson@petermac.org\"><span style=\" font-size:11pt; text-decoration: underline; color:#0000ff;\">Price Jackson</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"Disclaimer:\"></a><span style=\" font-family:\'arial,sans-serif\'; font-size:11pt; font-weight:600; color:#000000;\">D</span><span style=\" font-family:\'arial,sans-serif\'; font-size:11pt; font-weight:600; color:#000000;\">isclaimer:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'arial,sans-serif\'; font-size:11pt; color:#000000; background-color:#ffffff;\">The source code is distributed freely and without any warranty whatsoever. VRAK must be installed and used at the risk of the user.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'arial,sans-serif\'; font-size:11pt; color:#000000; background-color:#ffffff;\">VRAK is intended for educational, research and informational purposes only and may be used only for such purposes and may not under any circumstances whatsoever be used for clinical or diagnostic purposes (ie for treatment planning, risk assessment).</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.about_tab), QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.fixedCT_LE.setToolTip(QtGui.QApplication.translate("MainWindow", "CT File that will be used for alignment. All files should be registered to this image", None, QtGui.QApplication.UnicodeUTF8))
        self.fixedCT_toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.fixedCT_label.setText(QtGui.QApplication.translate("MainWindow", "Fixed CT Path", None, QtGui.QApplication.UnicodeUTF8))
        self.fixedSPECT_LE.setToolTip(QtGui.QApplication.translate("MainWindow", "CT File that will be used for alignment. All files should be registered to this image", None, QtGui.QApplication.UnicodeUTF8))
        self.fixedSPECT_toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.fixedCT_label_2.setText(QtGui.QApplication.translate("MainWindow", "Fixed PET/SPECT Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Timepoint 1 Input:", None, QtGui.QApplication.UnicodeUTF8))
        self.registerImages_button.setText(QtGui.QApplication.translate("MainWindow", "Register/Convert Images", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Note: Registration settings on next tab", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Batch Run Registration and Dose processing:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Image Times and Isotope must be selected", None, QtGui.QApplication.UnicodeUTF8))
        self.regNrun_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Register and Run Dosimetry", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "on Dosimetry Input Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.outputFixedCT_toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.oututCT_label_2.setText(QtGui.QApplication.translate("MainWindow", "Output Fixed CT Image (*.mhd)", None, QtGui.QApplication.UnicodeUTF8))
        self.outputFixedSPECT_toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.oututSPECT_label_2.setText(QtGui.QApplication.translate("MainWindow", "Output Fixed PET/SPECT (*.mhd)", None, QtGui.QApplication.UnicodeUTF8))
        self.imNum_label.setText(QtGui.QApplication.translate("MainWindow", "Use as Kinetics Image #:", None, QtGui.QApplication.UnicodeUTF8))
        self.convSPECTNum_Box.setItemText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.convSPECTNum_Box.setItemText(1, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.convSPECTNum_Box.setItemText(2, QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Output:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Note: Kinetics Input Images Must Be *.mhd Format, Convert Here", None, QtGui.QApplication.UnicodeUTF8))
        self.movingCT_LE.setToolTip(QtGui.QApplication.translate("MainWindow", "CT to be aligned to Fixed CT. This is used to create the transform for aligning SPECT/PET images.", None, QtGui.QApplication.UnicodeUTF8))
        self.movingCT_toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.movingCT_label.setText(QtGui.QApplication.translate("MainWindow", "Moving CT Path", None, QtGui.QApplication.UnicodeUTF8))
        self.movingSPECT_toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.movingSPECT_label.setText(QtGui.QApplication.translate("MainWindow", "Moving PET/SPECT Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Timepoint 2 Input:", None, QtGui.QApplication.UnicodeUTF8))
        self.outputCT_toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.oututCT_label.setText(QtGui.QApplication.translate("MainWindow", "Output Registered CT Image (*.mhd)", None, QtGui.QApplication.UnicodeUTF8))
        self.outputSPECT_toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.oututSPECT_label.setText(QtGui.QApplication.translate("MainWindow", "Output Registered PET/SPECT (*.mhd)", None, QtGui.QApplication.UnicodeUTF8))
        self.imNum_label_2.setText(QtGui.QApplication.translate("MainWindow", "Use as Kinetics Image #:", None, QtGui.QApplication.UnicodeUTF8))
        self.regSPECTNum_Box.setItemText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.regSPECTNum_Box.setItemText(1, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.regSPECTNum_Box.setItemText(2, QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Output:", None, QtGui.QApplication.UnicodeUTF8))
        self.movingCT_toolButton_2.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.movingCT_LE_2.setToolTip(QtGui.QApplication.translate("MainWindow", "CT to be aligned to Fixed CT. This is used to create the transform for aligning SPECT/PET images.", None, QtGui.QApplication.UnicodeUTF8))
        self.movingCT_label_2.setText(QtGui.QApplication.translate("MainWindow", "Moving CT Path", None, QtGui.QApplication.UnicodeUTF8))
        self.movingSPECT_toolButton_2.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.movingSPECT_label_2.setText(QtGui.QApplication.translate("MainWindow", "Moving PET/SPECT Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Timepoint 3 (optional) Input:", None, QtGui.QApplication.UnicodeUTF8))
        self.outputCT_toolButton_2.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.oututCT_label_3.setText(QtGui.QApplication.translate("MainWindow", "Output Registered CT Image (*.mhd)", None, QtGui.QApplication.UnicodeUTF8))
        self.outputSPECT_toolButton_2.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.oututSPECT_label_3.setText(QtGui.QApplication.translate("MainWindow", "Output Registered PET/SPECT (*.mhd)", None, QtGui.QApplication.UnicodeUTF8))
        self.imNum_label_3.setText(QtGui.QApplication.translate("MainWindow", "Use as Kinetics Image #:", None, QtGui.QApplication.UnicodeUTF8))
        self.regSPECTNum_Box_2.setItemText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.regSPECTNum_Box_2.setItemText(1, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.regSPECTNum_Box_2.setItemText(2, QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Output:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.registration_tab), QtGui.QApplication.translate("MainWindow", "Co-Register Images", None, QtGui.QApplication.UnicodeUTF8))
        self.defParam_label.setText(QtGui.QApplication.translate("MainWindow", "Deformable Registration Parameters:", None, QtGui.QApplication.UnicodeUTF8))
        self.res1_label.setText(QtGui.QApplication.translate("MainWindow", "Resolution 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.res1combo_label.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Value used for downsampling input images. Higher values indicate lower resolution and faster processing times [default=8]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.res1combo_label.setText(QtGui.QApplication.translate("MainWindow", "voxel Binning (higher value -> lower res)", None, QtGui.QApplication.UnicodeUTF8))
        self.res1_comboBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Value used for downsampling input images. Higher values indicate lower resolution and faster processing times [default=8]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.res1_comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.res1_comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.res1_comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.res1_comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.res1gridcombo_label.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Spacing of Deformation control points. Larger value uses in fewer control points. This can affect the \'smoothness\' of the deformed image [default=16]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.res1gridcombo_label.setText(QtGui.QApplication.translate("MainWindow", "Deformation Grid Spacing (voxels)", None, QtGui.QApplication.UnicodeUTF8))
        self.res1grid_comboBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Spacing of Deformation control points. Larger value uses in fewer control points. This can affect the \'smoothness\' of the deformed image [default=16]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.res1grid_comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.res1grid_comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.res1grid_comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.res1grid_comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.res1iterations_label.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Number of iterations at this resolution level [default=200]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.res1iterations_label.setText(QtGui.QApplication.translate("MainWindow", "Iterations", None, QtGui.QApplication.UnicodeUTF8))
        self.res1_lineEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Number of iterations at this resolution level [default=200]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.res1_lineEdit.setText(QtGui.QApplication.translate("MainWindow", "200", None, QtGui.QApplication.UnicodeUTF8))
        self.res2_label.setText(QtGui.QApplication.translate("MainWindow", "Resolution 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.res1_comboBox_2.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Value used for downsampling input images. Higher values indicate lower resolution and faster processing times [default=4]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.res1_comboBox_2.setItemText(0, QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.res1_comboBox_2.setItemText(1, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.res1_comboBox_2.setItemText(2, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.res1_comboBox_2.setItemText(3, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.res2gridcombo_label.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Spacing of Deformation control points. Larger value uses in fewer control points. This can affect the \'smoothness\' of the deformed image [default=8]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.res2gridcombo_label.setText(QtGui.QApplication.translate("MainWindow", "Deformation Grid Spacing (voxels)", None, QtGui.QApplication.UnicodeUTF8))
        self.res2grid_comboBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Spacing of Deformation control points. Larger value uses in fewer control points. This can affect the \'smoothness\' of the deformed image [default=8]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.res2grid_comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.res2grid_comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.res2grid_comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.res2grid_comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.res2iterations_label.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Number of iterations at this resolution level [default=150]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.res2iterations_label.setText(QtGui.QApplication.translate("MainWindow", "Iterations", None, QtGui.QApplication.UnicodeUTF8))
        self.res2_lineEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Number of iterations at this resolution level [default=150]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.res2_lineEdit.setText(QtGui.QApplication.translate("MainWindow", "150", None, QtGui.QApplication.UnicodeUTF8))
        self.res2iterations_label_2.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Rigidity penalty (value 0.0 to 1.0): Higher values result in smoother images. Adjusting this may correct unnatural warping [default=0.2]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.res2iterations_label_2.setText(QtGui.QApplication.translate("MainWindow", "Bending Energy Penalty", None, QtGui.QApplication.UnicodeUTF8))
        self.bendingPenalty_lineEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Rigidity penalty (value 0.0 to 1.0): Higher values result in smoother images. Adjusting this may correct unnatural warping [default=0.2]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.bendingPenalty_lineEdit.setText(QtGui.QApplication.translate("MainWindow", "0.2", None, QtGui.QApplication.UnicodeUTF8))
        self.res2combo_label.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Value used for downsampling input images. Higher values indicate lower resolution and faster processing times [default=4]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.res2combo_label.setText(QtGui.QApplication.translate("MainWindow", "voxel Binning (higher value -> lower res)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Registration Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Image 3:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Path to File (*.mhd):", None, QtGui.QApplication.UnicodeUTF8))
        self.im3_toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Time Post-Injection (hours)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Therapeutic radionuclide to be estimated. Dose convolved using 5mm Voxel S-Values from Geant4/GATE simalation. Note: Short half-life (&lt;24 hr) isotopes have not been validated.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Dosimetry Isotope:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Therapeutic radionuclide to be estimated. Dose convolved using 5mm Voxel S-Values from Geant4/GATE simalation. Note: Short half-life (&lt;24 hr) isotopes have not been validated.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "P-32", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Sr-89", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Y-90", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Tc-99m", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "In-111", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "I-131", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "Sm-153", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(7, QtGui.QApplication.translate("MainWindow", "Lu-177", None, QtGui.QApplication.UnicodeUTF8))
        self.halflife_lineedit.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Half-life is used for decay-correcting images before processing kinetics</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.halflife_lineedit.setText(QtGui.QApplication.translate("MainWindow", "161.04", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Image 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Path to File (*.mhd):", None, QtGui.QApplication.UnicodeUTF8))
        self.im1_toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Time Post-Injection (hours)", None, QtGui.QApplication.UnicodeUTF8))
        self.isotope_comboBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Half-life is used for decay-correcting images before processing kinetics</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.isotope_comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "User-defined", None, QtGui.QApplication.UnicodeUTF8))
        self.isotope_comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "P-32", None, QtGui.QApplication.UnicodeUTF8))
        self.isotope_comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Ga-68", None, QtGui.QApplication.UnicodeUTF8))
        self.isotope_comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Sr-89", None, QtGui.QApplication.UnicodeUTF8))
        self.isotope_comboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "Y-90", None, QtGui.QApplication.UnicodeUTF8))
        self.isotope_comboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "Tc-99m", None, QtGui.QApplication.UnicodeUTF8))
        self.isotope_comboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "In-111", None, QtGui.QApplication.UnicodeUTF8))
        self.isotope_comboBox.setItemText(7, QtGui.QApplication.translate("MainWindow", "I-123", None, QtGui.QApplication.UnicodeUTF8))
        self.isotope_comboBox.setItemText(8, QtGui.QApplication.translate("MainWindow", "I-131", None, QtGui.QApplication.UnicodeUTF8))
        self.isotope_comboBox.setItemText(9, QtGui.QApplication.translate("MainWindow", "Sm-153", None, QtGui.QApplication.UnicodeUTF8))
        self.isotope_comboBox.setItemText(10, QtGui.QApplication.translate("MainWindow", "Lu-177", None, QtGui.QApplication.UnicodeUTF8))
        self.isotope_comboBox.setItemText(11, QtGui.QApplication.translate("MainWindow", "Bi-213", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Physical Halflife (Hrs)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Half-life is used for decay-correcting images before processing kinetics</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Imaging Isotope:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Image 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Path to File (*.mhd):", None, QtGui.QApplication.UnicodeUTF8))
        self.im2_toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Time Post-Injection (hours)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Output Image (voxel values: Gy):", None, QtGui.QApplication.UnicodeUTF8))
        self.outputimage_toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.save_fit_checkBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Saves decay-corrected bi- or tri-exponential fit parameters into a NumPy array: [Z, Y, X, 4] (2-phase) or [Z, Y, X, 6] (3-phase)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.save_fit_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Save Fit Parameters?", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.input_tab), QtGui.QApplication.translate("MainWindow", "Dosimetry Input", None, QtGui.QApplication.UnicodeUTF8))
        self.runVRAK_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Run VRAK... ", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_Button.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.kinetics_tab), QtGui.QApplication.translate("MainWindow", "Process Dose", None, QtGui.QApplication.UnicodeUTF8))
        self.elastixPath_toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.elastixPath_label.setText(QtGui.QApplication.translate("MainWindow", "Elastix Path", None, QtGui.QApplication.UnicodeUTF8))
        self.transformixPath_toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.transformixPath_label.setText(QtGui.QApplication.translate("MainWindow", "Transformix Path", None, QtGui.QApplication.UnicodeUTF8))
        self.transformixPath_toolButton_2.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.transformixPath_label_2.setText(QtGui.QApplication.translate("MainWindow", "Work Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.configure_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Save Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.configure_textBrowser.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">You only need to configure executable paths once. Image Registration and Resampling require Elastix. The binaries can be downloaded from </span><a href=\"http://elastix.isi.uu.nl/\"><span style=\" font-size:11pt; text-decoration: underline; color:#0000ff;\">http://elastix.isi.uu.nl/</span></a><span style=\" font-size:11pt;\"> Once installed, input the path to the Elastix and Transformix executables and click \'Save\'.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Selecting a work directory will make this the default folder for writing output images.  Alternatively, unspecified output files will be given a generic name and saved in the program directory.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.config_tab), QtGui.QApplication.translate("MainWindow", "Configure", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))

